import { median } from './stats.js';
import { controlNormalize } from './comprehensive.js';

const uniq=a=>[...new Set(a.filter(v=>v!==''&&v!=null))];
const finite=a=>a.map(Number).filter(Number.isFinite);
const med=a=>{const v=finite(a);return v.length?median(v):NaN};
const mean=a=>{const v=finite(a);return v.length?v.reduce((x,y)=>x+y,0)/v.length:NaN};
const sd=a=>{const v=finite(a),m=mean(v);return v.length>1?Math.sqrt(v.reduce((s,x)=>s+(x-m)**2,0)/(v.length-1)):NaN};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PALETTE=['#315c45','#c89a45','#a85f47','#765767','#6d8b64','#55748b','#9a7558','#65806b','#8e6d77','#6f7a54'];
const HEAT=[[0,'#f4efe3'],[.25,'#dce7d6'],[.5,'#f9faf7'],[.75,'#e6c89a'],[1,'#a85f47']];

function base(y=''){return{margin:{l:62,r:18,t:10,b:52},paper_bgcolor:'#fff',plot_bgcolor:'#fff',font:{family:'Inter, ui-sans-serif, sans-serif',color:'#304035',size:11},xaxis:{gridcolor:'#edf0eb',zeroline:false,linecolor:'#d8ddd6',automargin:true},yaxis:{title:y,gridcolor:'#edf0eb',zeroline:false,linecolor:'#d8ddd6',automargin:true},legend:{orientation:'h',y:-.2,x:0,font:{size:10}},hovermode:'closest',showlegend:true}}
function card(root,id,title,desc,{wide=false}={}){const el=document.createElement('section');el.className=`visual-card${wide?' visual-wide':''}`;el.innerHTML=`<div class="visual-card-head"><div><h4>${esc(title)}</h4><p>${esc(desc)}</p></div><button class="ghost small visual-save" data-plot="${id}">SVG</button></div><div id="${id}" class="visual-plot"></div>`;root.appendChild(el);return el.querySelector('.visual-plot')}
function divider(root,label){const d=document.createElement('div');d.className='report-section-divider';d.textContent=label;root.appendChild(d)}
function plot(el,traces,layout){if(!el||!window.Plotly||!traces?.length){if(el)el.outerHTML='<div class="visual-placeholder">Not applicable to this dataset.</div>';return false}Plotly.react(el,traces,layout,{responsive:true,displaylogo:false,displayModeBar:false});return true}
function levels(rows,f){return f?uniq(rows.map(r=>r[f])):[]}
function color(i){return PALETTE[i%PALETTE.length]}
function groupSummary(rows,group,metric){return levels(rows,group).map(g=>{const v=finite(rows.filter(r=>r[group]===g).map(r=>r[metric])),m=mean(v),s=sd(v),se=v.length>1?s/Math.sqrt(v.length):NaN;return{group:g,n:v.length,mean:m,ci:Number.isFinite(se)?1.96*se:NaN,median:med(v)}}).filter(x=>Number.isFinite(x.mean))}
function boxTraces(rows,group,metric){const ls=levels(rows,group);if(ls.length>12)return[];return ls.map((g,i)=>({type:'box',name:String(g),y:finite(rows.filter(r=>r[group]===g).map(r=>r[metric])),boxpoints:'all',jitter:.22,pointpos:0,marker:{size:5,color:color(i),opacity:.72},line:{color:color(i),width:1.5},fillcolor:'rgba(255,255,255,0)'})).filter(t=>t.y.length)}
function summaryTrace(rows,group,metric){const s=groupSummary(rows,group,metric).sort((a,b)=>a.mean-b.mean);return s.length?[{type:'scatter',mode:'markers',x:s.map(x=>x.mean),y:s.map(x=>String(x.group)),error_x:{type:'data',array:s.map(x=>x.ci),visible:true,color:'#9aa39b',thickness:1},marker:{size:8,color:'#315c45'},customdata:s.map(x=>x.n),hovertemplate:'%{y}<br>mean=%{x:.3g}<br>n=%{customdata}<extra></extra>'}]:[]}
function lineTraces(rows,group,value='value'){const times=uniq(rows.map(r=>+r.time).filter(Number.isFinite)).sort((a,b)=>a-b),ls=levels(rows,group).slice(0,10);return ls.map((g,i)=>({type:'scatter',mode:'lines+markers',name:String(g),x:times,y:times.map(t=>med(rows.filter(r=>r[group]===g&&+r.time===t).map(r=>r[value]))),line:{width:2,color:color(i)},marker:{size:6,color:color(i)}}))}
function sampleCountTrace(rows,group){const s=levels(rows,group).map(g=>({g,n:rows.filter(r=>r[group]===g).length})).sort((a,b)=>a.n-b.n);return s.length?[{type:'bar',orientation:'h',x:s.map(x=>x.n),y:s.map(x=>String(x.g)),marker:{color:'#6d8b64'},hovertemplate:'%{y}<br>n=%{x}<extra></extra>'}]:[]}
function qcTrace(metrics){const counts=new Map([['clean',0]]);for(const r of metrics){const raw=String(r.qc_flags||'').trim();if(!raw){counts.set('clean',(counts.get('clean')||0)+1);continue}for(const f of raw.split(/[;,|]/).map(x=>x.trim()).filter(Boolean))counts.set(f,(counts.get(f)||0)+1)}const a=[...counts].sort((x,y)=>x[1]-y[1]);return a.length?[{type:'bar',orientation:'h',x:a.map(x=>x[1]),y:a.map(x=>x[0]),marker:{color:a.map(x=>x[0]==='clean'?'#6d8b64':'#a85f47')},hovertemplate:'%{y}<br>count=%{x}<extra></extra>'}]:[]}
function cvTrace(rows){const v=finite(rows.map(r=>r.cv));return v.length?[{type:'histogram',x:v,nbinsx:14,marker:{color:'#6d8b64',line:{color:'#fff',width:1}},hovertemplate:'CV=%{x:.3g}<br>count=%{y}<extra></extra>'}]:[]}
function effectTrace(tests){const a=tests.filter(r=>Number.isFinite(+r.hedges_g)&&Number.isFinite(+r.q));if(!a.length)return[];const top=[...a].sort((x,y)=>(+x.q)-(+y.q)||Math.abs(+y.hedges_g)-Math.abs(+x.hedges_g)).slice(0,6),topSet=new Set(top);return[{type:'scatter',mode:'markers+text',x:a.map(r=>+r.hedges_g),y:a.map(r=>-Math.log10(Math.max(+r.q,1e-12))),text:a.map(r=>topSet.has(r)?String(r.group):''),textposition:'top center',textfont:{size:9,color:'#536058'},marker:{size:a.map(r=>topSet.has(r)?10:7),color:a.map(r=>+r.q<.05?'#a85f47':'#6d8b64'),opacity:.78},hovertemplate:'%{text}<br>Hedges g=%{x:.3g}<br>-log10(q)=%{y:.3g}<extra></extra>'}]
}
function rankTrace(rows,group){const a=rows.filter(r=>Number.isFinite(+r.relative_fitness)).sort((x,y)=>x.relative_fitness-y.relative_fitness).slice(0,30);return a.length?[{type:'bar',orientation:'h',x:a.map(r=>+r.relative_fitness),y:a.map(r=>String(r[group]??r.rank)),marker:{color:a.map(r=>+r.relative_fitness<1?'#a85f47':'#6d8b64')},customdata:a.map(r=>r.median_robust_z),hovertemplate:'%{y}<br>relative=%{x:.3g}<br>robust Z=%{customdata:.3g}<extra></extra>'}]:[]}
function normalizedBox(rows,group,metric,cfg){if(!cfg.controlField)return[];const n=controlNormalize(rows,metric,cfg),ls=levels(n,group);if(ls.length>12)return[];return ls.map((g,i)=>({type:'box',name:String(g),y:finite(n.filter(r=>r[group]===g).map(r=>r.relative_to_control)),boxpoints:'all',jitter:.22,pointpos:0,marker:{size:5,color:color(i),opacity:.7},line:{color:color(i)}})).filter(t=>t.y.length)}
function timeHeatmap(rows,group){const times=uniq(rows.map(r=>+r.time).filter(Number.isFinite)).sort((a,b)=>a-b),ls=levels(rows,group);if(!times.length||!ls.length||ls.length>30)return[];return[{type:'heatmap',x:times,y:ls,z:ls.map(g=>times.map(t=>med(rows.filter(r=>r[group]===g&&+r.time===t).map(r=>r.relative_to_control))),zmid:1,colorscale:HEAT,colorbar:{title:'Rel.',thickness:12},hovertemplate:`${group}=%{y}<br>time=%{x}<br>relative=%{z:.3g}<extra></extra>`}]
}
function factorialHeatmap(rows){if(!rows?.length)return[];const meta=Object.keys(rows[0]).filter(k=>!['n','mean','median','sd','sem','ci95_low','ci95_high','cv','min','max'].includes(k));if(meta.length<2)return[];const[a,b]=meta,al=uniq(rows.map(r=>r[a])),bl=uniq(rows.map(r=>r[b]));return[{type:'heatmap',x:bl,y:al,z:al.map(x=>bl.map(y=>rows.find(r=>r[a]===x&&r[b]===y)?.median??NaN)),colorscale:'YlGnBu',colorbar:{title:'Median',thickness:12},hovertemplate:`${a}=%{y}<br>${b}=%{x}<br>median=%{z:.3g}<extra></extra>`}]
}
function doseTrace(rows,dose,group){const ls=group?levels(rows,group):['all'];return ls.slice(0,10).map((g,i)=>{const rr=group?rows.filter(r=>r[group]===g):rows,d=uniq(rr.map(r=>+r[dose]).filter(Number.isFinite)).sort((a,b)=>a-b);return{type:'scatter',mode:'lines+markers',name:String(g),x:d,y:d.map(x=>med(rr.filter(r=>+r[dose]===x).map(r=>r.value))),line:{width:2,color:color(i)},marker:{size:6,color:color(i)}}})}
function competitionLogit(rows,group){const ls=group?levels(rows,group):['all'];return ls.slice(0,10).map((g,i)=>{const rr=group?rows.filter(r=>r[group]===g):rows,t=uniq(rr.map(r=>+r.time).filter(Number.isFinite)).sort((a,b)=>a-b);return{type:'scatter',mode:'lines+markers',name:String(g),x:t,y:t.map(x=>{const f=med(rr.filter(r=>+r.time===x).map(r=>r.value));return f>0&&f<1?Math.log(f/(1-f)):NaN}),line:{width:2,color:color(i)},marker:{size:6,color:color(i)}}})}
function correlationTrace(rows){const ms=['mu_max','doubling_time','lag','auc','max_value','endpoint','trend_slope','absolute_change','fold_change'].filter(m=>rows.filter(r=>Number.isFinite(+r[m])).length>=3);if(ms.length<2)return[];const corr=(a,b)=>{const pairs=rows.map(r=>[+r[a],+r[b]]).filter(([x,y])=>Number.isFinite(x)&&Number.isFinite(y));if(pairs.length<3)return NaN;const xm=mean(pairs.map(x=>x[0])),ym=mean(pairs.map(x=>x[1])),num=pairs.reduce((s,[x,y])=>s+(x-xm)*(y-ym),0),dx=Math.sqrt(pairs.reduce((s,[x])=>s+(x-xm)**2,0)),dy=Math.sqrt(pairs.reduce((s,[,y])=>s+(y-ym)**2,0));return dx&&dy?num/(dx*dy):NaN};return[{type:'heatmap',x:ms,y:ms,z:ms.map(a=>ms.map(b=>corr(a,b))),zmin:-1,zmax:1,zmid:0,colorscale:HEAT,colorbar:{title:'r',thickness:12},hovertemplate:'%{y} × %{x}<br>r=%{z:.3f}<extra></extra>'}]
}
function metricGrid(root,metrics,group){const ms=['mu_max','doubling_time','lag','auc','max_value','endpoint','trend_slope','absolute_change','fold_change'].filter(m=>metrics.some(r=>Number.isFinite(+r[m])));for(const m of ms){const el=card(root,`viz_metric_${m}`,m.replaceAll('_',' '),`Biological-replicate distribution of ${m.replaceAll('_',' ')}.`);let lo=base(m.replaceAll('_',' '));lo.xaxis.title=group;lo.showlegend=false;const bt=boxTraces(metrics,group,m);plot(el,bt.length?bt:summaryTrace(metrics,group,m),lo)}}

export function renderVisualDashboard(root,{S,data,group,metric}){
  if(!root)return;root.innerHTML='';const preset=S.design.preset||'manual',points=data.inferencePoints||[],metrics=data.inferenceMetrics||S.metrics||[],normPoints=data.normalizedPoints||[],cfg={controlField:S.design.controlField||'',controlValue:S.design.controlValue||'control',strata:S.design.controlStrata||[]};
  const tests=data.metricTests?.length?data.metricTests:(data.timepointTests||[]),hasTime=points.some(r=>Number.isFinite(+r.time)),primary=metric||['endpoint','auc','max_value','trend_slope'].find(m=>metrics.some(r=>Number.isFinite(+r[m])))||'';
  const intro=document.createElement('div');intro.className='visual-report-head';intro.innerHTML=`<div><span class="section-tag">VISUAL REPORT</span><h3>${esc(S.design.presetName||'Comprehensive analysis')}</h3><p>Every experiment receives the same core views for magnitude, uncertainty, controls, statistics, sample size, and QC. Design-specific views are added below when supported.</p></div><span>${esc(preset)}</span>`;root.appendChild(intro);const grid=document.createElement('div');grid.className='visual-grid';root.appendChild(grid);

  divider(grid,'Core report · always attempted');
  if(hasTime&&group){const el=card(grid,'viz_observed','Observed measurements','Biological-level median at each sampled timepoint.',{wide:true});const lo=base('Measurement');lo.xaxis.title=`Time (${S.design.timeUnit||'units'})`;plot(el,lineTraces(points,group,'value'),lo)}
  if(group&&primary){const el=card(grid,'viz_primary','Primary phenotype distribution',`Biological replicates for ${primary.replaceAll('_',' ')}.`);let lo=base(primary.replaceAll('_',' '));lo.xaxis.title=group;lo.showlegend=false;const bt=boxTraces(metrics,group,primary);plot(el,bt.length?bt:summaryTrace(metrics,group,primary),lo)}
  if(group&&primary){const el=card(grid,'viz_group_summary','Group estimate + 95% CI',`Mean ${primary.replaceAll('_',' ')} with approximate 95% CI and biological n.`);let lo=base();lo.xaxis.title=primary.replaceAll('_',' ');lo.yaxis.title=group;lo.showlegend=false;plot(el,summaryTrace(metrics,group,primary),lo)}
  if(group&&primary&&cfg.controlField){const el=card(grid,'viz_normalized','Matched-control normalization','Biological observations relative to the selected control within normalization strata.');let lo=base('Relative to control');lo.xaxis.title=group;lo.showlegend=false;lo.shapes=[{type:'line',x0:-.5,x1:Math.max(.5,levels(metrics,group).length-.5),y0:1,y1:1,line:{color:'#9aa39b',dash:'dot',width:1}}];const bt=normalizedBox(metrics,group,primary,cfg);plot(el,bt.length?bt:rankTrace(data.ranking||[],group),lo)}
  if(tests.length){const el=card(grid,'viz_effects','Effect size vs statistical evidence','Standardized effect size together with FDR-adjusted evidence. Only the strongest points are labeled.');let lo=base('-log10(q)');lo.xaxis.title='Hedges’ g';lo.showlegend=false;plot(el,effectTrace(tests),lo)}
  if(group){const el=card(grid,'viz_n','Biological sample size','Number of biological-level observations contributing to each group.');let lo=base('');lo.xaxis.title='Biological n';lo.showlegend=false;plot(el,sampleCountTrace(metrics,group),lo)}
  {const el=card(grid,'viz_qc','QC flag overview','Counts of clean analysis units and each QC warning. Flags remain visible; they are not silently excluded.');let lo=base('');lo.xaxis.title='Analysis units';lo.showlegend=false;plot(el,qcTrace(metrics),lo)}
  if(data.replicates?.length){const el=card(grid,'viz_cv','Technical-replicate precision','Coefficient of variation across technical measurements of the same biological unit.');let lo=base('Count');lo.xaxis.title='Technical replicate CV';lo.showlegend=false;plot(el,cvTrace(data.replicates),lo)}
  if(group&&data.ranking?.length){const el=card(grid,'viz_rank','Ranked relative phenotype','Control-normalized magnitude view. At most 30 groups are shown for readability.',{wide:true});let lo=base('');lo.xaxis.title='Relative phenotype';lo.yaxis.title=group;lo.showlegend=false;lo.shapes=[{type:'line',x0:1,x1:1,y0:-.5,y1:29.5,line:{color:'#9aa39b',dash:'dot',width:1}}];plot(el,rankTrace(data.ranking,group),lo)}
  if(metrics.length){const tr=correlationTrace(metrics);if(tr.length){const el=card(grid,'viz_corr','Metric correlation','Relationships among available per-unit metrics. Interpret correlation as descriptive.',{wide:true});let lo=base('');lo.xaxis.tickangle=-30;lo.showlegend=false;plot(el,tr,lo)}}
  if(hasTime&&group&&normPoints.length){const el=card(grid,'viz_time_heatmap','Relative phenotype across time','Median contemporaneous-control ratio by group and sampled timepoint.',{wide:true});let lo=base('');lo.xaxis.title=`Time (${S.design.timeUnit||'units'})`;lo.yaxis.title=group;lo.showlegend=false;plot(el,timeHeatmap(normPoints,group),lo)}

  divider(grid,'Design-specific views');
  if(['daily','evolution','competition'].includes(preset)&&group){for(const m of ['endpoint','auc','trend_slope','absolute_change','fold_change'].filter(x=>metrics.some(r=>Number.isFinite(+r[x])))){const el=card(grid,`viz_serial_${m}`,m.replaceAll('_',' '),`Complementary longitudinal summary using biological replicates.`);let lo=base(m.replaceAll('_',' '));lo.xaxis.title=group;lo.showlegend=false;const bt=boxTraces(metrics,group,m);plot(el,bt.length?bt:summaryTrace(metrics,group,m),lo)}}
  if(preset==='screen'&&group&&data.ranking?.length){const a=data.ranking.filter(x=>Number.isFinite(+x.relative_fitness)&&Number.isFinite(+x.median_robust_z));const el=card(grid,'viz_screen_z','Screen prioritization map','Relative phenotype versus robust Z. Candidate labels are intentionally limited.',{wide:true});let lo=base('Robust Z');lo.xaxis.title='Relative phenotype';lo.showlegend=false;const top=[...a].sort((x,y)=>Math.abs(+y.median_robust_z)-Math.abs(+x.median_robust_z)).slice(0,8),set=new Set(top);plot(el,a.length?[{type:'scatter',mode:'markers+text',x:a.map(x=>+x.relative_fitness),y:a.map(x=>+x.median_robust_z),text:a.map(x=>set.has(x)?String(x[group]):''),textposition:'top center',marker:{size:8,color:a.map(x=>Math.abs(+x.median_robust_z)>=2?'#a85f47':'#6d8b64'),opacity:.78}}]:[],lo)}
  if((preset==='matrix'||preset==='manual')&&data.factorial?.length){const el=card(grid,'viz_factorial','Factorial landscape','Median phenotype across the first two detected experimental factors.',{wide:true});let lo=base('');lo.showlegend=false;plot(el,factorialHeatmap(data.factorial),lo)}
  if(preset==='dose'){const dose=(S.factors||[]).find(x=>/dose|concentration|conc/i.test(x));if(dose){const el=card(grid,'viz_dose','Dose-response profile','Median biological response at each observed concentration.',{wide:true});let lo=base('Response');lo.xaxis.title=dose;plot(el,doseTrace(points.length?points:metrics,dose,group),lo)}if(data.dose?.length){const label=Object.keys(data.dose[0]).find(k=>!['baseline_response','extreme_response','half_response_target','half_response_dose','n_doses','direction'].includes(k));const el=card(grid,'viz_halfdose','Half-response estimate','Observed-range midpoint estimates where the response crosses its half-response target.');let lo=base('Half-response dose');lo.showlegend=false;plot(el,[{type:'bar',x:data.dose.map((x,i)=>String(label?x[label]:i+1)),y:data.dose.map(x=>+x.half_response_dose),marker:{color:'#315c45'}}],lo)}}
  if(preset==='competition'){const el=card(grid,'viz_logit','Logit-frequency trajectory','Linear trends in logit frequency form the selection-coefficient proxy.',{wide:true});let lo=base('logit(frequency)');lo.xaxis.title=`Time (${S.design.timeUnit||'units'})`;plot(el,competitionLogit(points,group),lo);if(data.competition?.length){const f=Object.keys(data.competition[0]).find(k=>/strain|genotype|line|sample/i.test(k));const e=card(grid,'viz_selection','Selection coefficient proxy','Slope of logit frequency versus time for each competition unit.');lo=base('Selection coefficient proxy');lo.showlegend=false;plot(e,[{type:'bar',x:data.competition.map((r,i)=>String(f?r[f]:i+1)),y:data.competition.map(r=>+r.selection_coefficient_proxy),marker:{color:'#315c45'}}],lo)}}
  if(preset==='kinetic'&&group)metricGrid(grid,metrics,group);

  root.querySelectorAll('.visual-save').forEach(b=>b.onclick=()=>window.Plotly&&Plotly.downloadImage(b.dataset.plot,{format:'svg',filename:`JhuangLab_YeastFit_${b.dataset.plot}`,height:650,width:950}));
}
