import { median } from './stats.js';
import { controlNormalize, twoByTwoInteraction, competitionSelection } from './comprehensive.js';

const api=window.YeastFit;
const S=api?.S;
const uniq=a=>[...new Set(a.filter(v=>v!==''&&v!=null))];
const finite=a=>a.map(Number).filter(Number.isFinite);
const med=a=>{const v=finite(a);return v.length?median(v):NaN};
const mean=a=>{const v=finite(a);return v.length?v.reduce((x,y)=>x+y,0)/v.length:NaN};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const COLORS=['#315c45','#c89a45','#a85f47','#765767','#55748b','#6d8b64','#9a7558','#65806b'];
const metricName=m=>String(m||'value').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());

function groupField(){const f=S?.factors||[];return f.find(x=>/genotype|strain/i.test(x))||f.find(x=>/condition|treatment|medium|carbon|drug/i.test(x))||f[0]||'';}
function levels(rows,f){return f?uniq(rows.map(r=>r[f])):[]}
function base(y=''){return{margin:{l:62,r:18,t:8,b:52},paper_bgcolor:'#fff',plot_bgcolor:'#fff',font:{family:'Inter, ui-sans-serif, sans-serif',color:'#304035',size:11},xaxis:{gridcolor:'#edf0eb',zeroline:false,linecolor:'#d8ddd6',automargin:true},yaxis:{title:y,gridcolor:'#edf0eb',zeroline:false,linecolor:'#d8ddd6',automargin:true},legend:{orientation:'h',y:-.2,x:0,font:{size:10}},hovermode:'closest',showlegend:true};}
function addCard(grid,id,title,desc,traces,layout,{wide=false}={}){if(!window.Plotly||!traces?.length)return false;const el=document.createElement('section');el.className=`visual-card extra-visual-card${wide?' visual-wide':''}`;el.innerHTML=`<div class="visual-card-head"><div><h4>${esc(title)}</h4><p>${esc(desc)}</p></div><button class="ghost small visual-save" data-plot="${id}">SVG</button></div><div id="${id}" class="visual-plot"></div>`;grid.appendChild(el);Plotly.react(el.querySelector('.visual-plot'),traces,layout,{responsive:true,displaylogo:false,displayModeBar:false});return true;}
function boxOrDot(rows,group,metric){if(!group||!metric)return[];const ls=levels(rows,group),valid=ls.map(g=>({g,v:finite(rows.filter(r=>r[group]===g).map(r=>r[metric]))})).filter(x=>x.v.length);if(!valid.length)return[];if(valid.length<=10)return valid.map((x,i)=>({type:'box',name:String(x.g),y:x.v,boxpoints:'all',jitter:.22,pointpos:0,marker:{size:5,color:COLORS[i%COLORS.length],opacity:.72},line:{color:COLORS[i%COLORS.length],width:1.4},fillcolor:'rgba(255,255,255,0)',hovertemplate:`${esc(metricName(metric))}=%{y:.4g}<extra>${esc(String(x.g))}</extra>`}));const s=valid.map(x=>({g:x.g,m:mean(x.v),n:x.v.length})).sort((a,b)=>a.m-b.m);return[{type:'scatter',mode:'markers',x:s.map(x=>x.m),y:s.map(x=>String(x.g)),marker:{size:8,color:'#315c45'},customdata:s.map(x=>x.n),hovertemplate:'%{y}<br>mean=%{x:.4g}<br>n=%{customdata}<extra></extra>'}];}
function metricCard(grid,rows,group,m,id){const tr=boxOrDot(rows,group,m);if(!tr.length)return false;const lo=base(metricName(m));lo.xaxis.title=tr[0]?.type==='scatter'?'':group;lo.showlegend=false;return addCard(grid,id,metricName(m),`Additional biological-level view of ${metricName(m).toLowerCase()}.`,tr,lo);}
function lineAcrossFactor(rows,group,factor,value='value'){if(!group||!factor)return[];const gl=levels(rows,group).slice(0,10),fl=levels(rows,factor);if(gl.length<2||fl.length<2)return[];const numeric=fl.every(v=>Number.isFinite(+v)),x=numeric?[...fl].map(Number).sort((a,b)=>a-b):fl;return gl.map((g,i)=>({type:'scatter',mode:'lines+markers',name:String(g),x,y:x.map(v=>med(rows.filter(r=>r[group]===g&&String(r[factor])===String(v)).map(r=>r[value]))),line:{width:2,color:COLORS[i%COLORS.length]},marker:{size:6,color:COLORS[i%COLORS.length]},connectgaps:false})).filter(t=>t.y.some(Number.isFinite));}
function robustScreenTrace(rows,group,metric){if(!group||!metric)return[];const groups=levels(rows,group),vals=groups.map(g=>({g,m:med(rows.filter(r=>r[group]===g).map(r=>r[metric]))})).filter(x=>Number.isFinite(x.m));if(vals.length<5)return[];const center=med(vals.map(x=>x.m)),mad=med(vals.map(x=>Math.abs(x.m-center)));if(!Number.isFinite(mad)||mad===0)return[];const a=vals.map(x=>({...x,z:.67448975*(x.m-center)/mad})).sort((x,y)=>x.z-y.z).slice(0,40);return[{type:'bar',orientation:'h',x:a.map(r=>r.z),y:a.map(r=>String(r.g)),marker:{color:a.map(r=>Math.abs(r.z)>=2.5?'#a85f47':'#6d8b64')},hovertemplate:'%{y}<br>robust Z=%{x:.3g}<extra></extra>'}];}
function doseSummary(rows,group,dose,kind){if(!group||!dose)return[];const out=[];for(const g of levels(rows,group)){const d=levels(rows.filter(r=>r[group]===g),dose).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(d.length<3)continue;const ys=d.map(x=>med(rows.filter(r=>r[group]===g&&+r[dose]===x).map(r=>r.value??r.endpoint)));if(ys.filter(Number.isFinite).length<3)continue;if(kind==='auc'){let auc=0;for(let i=1;i<d.length;i++)if(Number.isFinite(ys[i-1])&&Number.isFinite(ys[i]))auc+=(d[i]-d[i-1])*(ys[i-1]+ys[i])/2;out.push({g,v:auc});}else{out.push({g,v:ys[ys.length-1]-ys[0]});}}if(!out.length)return[];return[{type:'bar',orientation:out.length>6?'h':'v',x:out.length>6?out.map(r=>r.v):out.map(r=>String(r.g)),y:out.length>6?out.map(r=>String(r.g)):out.map(r=>r.v),marker:{color:'#315c45'},hovertemplate:out.length>6?'%{y}<br>value=%{x:.4g}<extra></extra>':'%{x}<br>value=%{y:.4g}<extra></extra>'}];}
function competitionFitTrace(rows){const a=(rows||[]).filter(r=>Number.isFinite(+r.selection_coefficient_proxy)&&Number.isFinite(+r.logit_trend_r2));if(a.length<2)return[];return[{type:'scatter',mode:'markers',x:a.map(r=>+r.selection_coefficient_proxy),y:a.map(r=>+r.logit_trend_r2),marker:{size:8,color:'#315c45',opacity:.8},hovertemplate:'s proxy=%{x:.4g}<br>R²=%{y:.3f}<extra></extra>'}];}
function interactionTrace(rows,a,b,value='value'){const x=twoByTwoInteraction(rows,a,b,value);if(!x||!Number.isFinite(+x.interaction))return[];return[{type:'bar',x:['Interaction'],y:[+x.interaction],marker:{color:+x.interaction<0?'#a85f47':'#315c45'},hovertemplate:'difference-in-differences=%{y:.4g}<extra></extra>'}];}

function buildExtra(grid){const preset=S?.design?.preset||'manual',metrics=S?.metrics||[],points=(S?.adj||[]).filter(r=>Number.isFinite(+r.value)),group=groupField(),factors=(S?.factors||[]).filter(Boolean),cfg={controlField:S?.design?.controlField||'',controlValue:S?.design?.controlValue||'control',strata:S?.design?.controlStrata||[]};let n=0;const add=(...args)=>{if(metricCard(...args))n++};
  if(preset==='daily'){for(const m of ['absolute_change','log2_fold_change','max_value','time_to_threshold','trend_r2'])if(metrics.some(r=>Number.isFinite(+r[m])))add(grid,metrics,group,m,`extra_${m}`);}
  else if(preset==='evolution'){for(const m of ['auc','absolute_change','log2_fold_change','trend_r2','max_value'])if(metrics.some(r=>Number.isFinite(+r[m])))add(grid,metrics,group,m,`extra_${m}`);}
  else if(preset==='kinetic'){for(const m of ['max_value','endpoint','time_to_threshold','growth_r2'])if(metrics.some(r=>Number.isFinite(+r[m])))add(grid,metrics,group,m,`extra_${m}`);}
  else if(preset==='screen'){
    const primary=['endpoint','auc','max_value'].find(m=>metrics.some(r=>Number.isFinite(+r[m])));
    let screenRows=metrics,screenMetric=primary;
    if(primary&&cfg.controlField){const norm=controlNormalize(metrics,primary,cfg);if(norm.some(r=>Number.isFinite(+r.relative_to_control))){screenRows=norm;screenMetric='relative_to_control';}}
    const rz=robustScreenTrace(screenRows,group,screenMetric);if(rz.length){const lo=base('');lo.xaxis.title='Robust Z';lo.showlegend=false;if(addCard(grid,'extra_robust_z','Robust-Z screen view','Robust standardized control-normalized phenotype across screened groups.',rz,lo,{wide:true}))n++;}
    if(primary)add(grid,metrics,group,primary,'extra_screen_distribution');
  }
  else if(preset==='matrix'){const f=factors.find(x=>x!==group&&/condition|medium|media|treatment|drug|carbon|stress|environment/i.test(x))||factors.find(x=>x!==group);if(f){const tr=lineAcrossFactor(points.length?points:metrics,group,f,points.length?'value':'endpoint');if(tr.length){const lo=base('Phenotype');lo.xaxis.title=f;if(addCard(grid,'extra_condition_profiles','Condition profiles','Group-specific profiles across conditions reveal crossing and context-dependent effects.',tr,lo,{wide:true}))n++;}const inter=interactionTrace(points.length?points:metrics,group,f,points.length?'value':'endpoint');if(inter.length){const lo=base('Interaction contrast');lo.showlegend=false;if(addCard(grid,'extra_interaction','2 × 2 interaction contrast','Difference-in-differences when both factors have exactly two levels.',inter,lo))n++;}}}
  else if(preset==='dose'){const dose=factors.find(x=>/dose|concentration|conc/i.test(x));if(dose){const source=points.length?points:metrics;for(const kind of ['auc','span']){const tr=doseSummary(source,group,dose,kind);if(tr.length){const lo=base(kind==='auc'?'Response AUC':'Response change');lo.showlegend=false;const title=kind==='auc'?'Dose-integrated response':'Response span';if(addCard(grid,`extra_dose_${kind}`,title,kind==='auc'?'Trapezoidal response integrated across the observed dose range.':'Change from lowest to highest observed dose.',tr,lo,{wide:true}))n++;}}}}
  else if(preset==='competition'){
    const idFields=uniq([group,...factors.filter(f=>f!==group),S?.design?.bioRepField,S?.design?.batchField].filter(Boolean)).filter(f=>points.some(r=>Object.prototype.hasOwnProperty.call(r,f))).slice(0,5);
    const comp=points.length?competitionSelection(points,{idFields,timeField:'time',valueField:'value'}):[];
    const tr=competitionFitTrace(comp);if(tr.length){const lo=base('Logit-fit R²');lo.xaxis.title='Selection-coefficient proxy';lo.showlegend=false;if(addCard(grid,'extra_comp_fit','Selection estimate vs fit quality','Checks whether large selection estimates are supported by a well-behaved logit trend.',tr,lo,{wide:true}))n++;}
    for(const m of ['endpoint','trend_slope'])if(metrics.some(r=>Number.isFinite(+r[m])))add(grid,metrics,group,m,`extra_${m}`);
  }
  else {for(const m of ['auc','absolute_change','log2_fold_change','trend_slope','max_value','time_to_threshold','growth_r2'].filter(m=>metrics.some(r=>Number.isFinite(+r[m]))).slice(0,6))add(grid,metrics,group,m,`extra_${m}`);if(factors.length>=2){const f=factors.find(x=>x!==group);const tr=lineAcrossFactor(points.length?points:metrics,group,f,points.length?'value':'endpoint');if(tr.length){const lo=base('Phenotype');lo.xaxis.title=f;if(addCard(grid,'extra_factor_profile','Factor profile','Additional factor-aware view of the phenotype.',tr,lo,{wide:true}))n++;}}}
  return n;
}
function injectStyle(){if(document.querySelector('#yeastfit-extra-style'))return;const s=document.createElement('style');s.id='yeastfit-extra-style';s.textContent=`.visual-more{margin-top:18px;border:1px solid #dfe5dc;border-radius:14px;background:#fbfcfa}.visual-more>summary{cursor:pointer;padding:15px 18px;font-weight:700;color:#315c45;list-style:none}.visual-more>summary::-webkit-details-marker{display:none}.visual-more>summary:after{content:'+';float:right;font-size:20px;font-weight:500}.visual-more[open]>summary:after{content:'–'}.visual-more-note{padding:0 18px 12px;color:#68746c;font-size:13px}.visual-more .extra-grid{padding:0 14px 14px}.extra-visual-card{background:#fff}.visual-more[open] .visual-plot{min-height:280px}@media(max-width:700px){.visual-more .extra-grid{padding:0 8px 10px}.visual-more>summary{padding:14px}.visual-more[open] .visual-plot{min-height:250px}}`;document.head.appendChild(s);}
function render(){if(!S?.metrics?.length||!window.Plotly)return;const root=document.querySelector('#visualDashboard');if(!root||root.querySelector('#visualMoreAnalyses'))return;const details=document.createElement('details');details.id='visualMoreAnalyses';details.className='visual-more';const summary=document.createElement('summary');summary.textContent='More analyses';const note=document.createElement('div');note.className='visual-more-note';note.textContent='Additional valid views are kept here so the main report stays readable. Empty or unsupported analyses remain hidden.';const grid=document.createElement('div');grid.className='visual-grid extra-grid';details.append(summary,note,grid);const n=buildExtra(grid);if(!n)return;summary.textContent=`More analyses · ${n} additional figure${n===1?'':'s'}`;root.appendChild(details);root.querySelectorAll('.visual-save').forEach(b=>{if(b.dataset.extraBound)return;b.dataset.extraBound='1';b.addEventListener('click',()=>{const id=b.dataset.plot;if(window.Plotly&&id)Plotly.downloadImage(id,{format:'svg',filename:`YeastFit_${id}`,height:700,width:1100})})});}
injectStyle();
let queued=false;const schedule=()=>{if(queued)return;queued=true;setTimeout(()=>{queued=false;render()},120)};new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();
