import fs from 'node:fs';

function replaceOnce(text,needle,repl){if(!text.includes(needle))throw new Error(`Missing patch target: ${needle}`);return text.replace(needle,repl)}

let html=fs.readFileSync('index.html','utf8');
if(!html.includes('styles-v05.css'))html=replaceOnce(html,'  <link rel="stylesheet" href="styles-advanced.css" />','  <link rel="stylesheet" href="styles-advanced.css" />\n  <link rel="stylesheet" href="styles-v05.css" />');
if(!html.includes('workflow-v05.js'))html=replaceOnce(html,'  <script type="module" src="js/presets.js"></script>','  <script type="module" src="js/presets.js"></script>\n  <script type="module" src="js/workflow-v05.js"></script>');
fs.writeFileSync('index.html',html);

let advanced=fs.readFileSync('js/advanced.js','utf8');
const oldKeys=`function biologicalKeyFields(rows, includeTime=true) {\n  const candidate=[...(S.factors||[]),S.design.controlField,...(S.design.controlStrata||[]),S.design.bioRepField,S.design.batchField,fieldByName(rows,/^sample$|sample_id|culture_id/i),includeTime?'time':''].filter(Boolean);\n  return uniq(candidate).filter(f=>f!==S.design.techRepField&&has(rows,f));\n}`;
const newKeys=`function biologicalKeyFields(rows, includeTime=true) {\n  const sampleFallback=S.design.bioRepField?'':fieldByName(rows,/^sample$|sample_id|culture_id/i);\n  const timeKey=includeTime&&rows.some(r=>Number.isFinite(+r.time))?'time':'';\n  const candidate=[...(S.factors||[]),S.design.controlField,...(S.design.controlStrata||[]),S.design.bioRepField,S.design.batchField,sampleFallback,timeKey].filter(Boolean);\n  return uniq(candidate).filter(f=>f!==S.design.techRepField&&has(rows,f));\n}`;
if(advanced.includes(oldKeys))advanced=advanced.replace(oldKeys,newKeys);
const oldPoint=`  const out={};\n  const pointGroupFields=uniq([group,...cfg.strata,'time'].filter(Boolean));\n  out.timepointSummary=pts.length?summarizeBy(pts,pointGroupFields,'value'):[];\n  out.normalizedPoints=pts.length&&cfg.controlField?controlNormalize(pts,'value',{...cfg,strata:uniq([...cfg.strata,'time'])}):[];\n  out.timepointTests=pts.length&&group?filteredTests(pts,'value',group,cfg,uniq([...cfg.strata,'time'])):[];\n  out.replicates=rawPts.length?replicateDiagnostics(rawPts,{technicalField:S.design.techRepField,biologicalField:S.design.bioRepField,timeField:'time',groupingFields:uniq([group,...cfg.strata].filter(Boolean)),cvWarn:0.15}):[];`;
const newPoint=`  const out={};\n  const hasTime=pts.some(r=>Number.isFinite(+r.time));\n  const pointStrata=uniq([...cfg.strata,hasTime?'time':''].filter(Boolean));\n  const pointGroupFields=uniq([group,...pointStrata].filter(Boolean));\n  out.timepointSummary=pts.length?summarizeBy(pts,pointGroupFields,'value'):[];\n  out.normalizedPoints=pts.length&&cfg.controlField?controlNormalize(pts,'value',{...cfg,strata:pointStrata}):[];\n  out.timepointTests=pts.length&&group?filteredTests(pts,'value',group,cfg,pointStrata):[];\n  out.replicates=rawPts.length?replicateDiagnostics(rawPts,{technicalField:S.design.techRepField,biologicalField:S.design.bioRepField,timeField:hasTime?'time':'',groupingFields:uniq([group,...cfg.strata].filter(Boolean)),cvWarn:0.15}):[];`;
if(advanced.includes(oldPoint))advanced=advanced.replace(oldPoint,newPoint);
fs.writeFileSync('js/advanced.js',advanced);

let dashboard=fs.readFileSync('js/dashboard.js','utf8');
const bad="z:ls.map(g=>times.map(t=>med(rows.filter(r=>r[group]===g&&+r.time===t).map(r=>r.relative_to_control))),zmid:1";
const good="z:ls.map(g=>times.map(t=>med(rows.filter(r=>r[group]===g&&+r.time===t).map(r=>r.relative_to_control)))),zmid:1";
if(dashboard.includes(bad))dashboard=dashboard.replace(bad,good);
dashboard=dashboard.replace("for(const m of ['endpoint','auc','trend_slope','absolute_change','fold_change'].filter(x=>metrics.some(r=>Number.isFinite(+r[x]))))","for(const m of ['endpoint','auc','trend_slope','absolute_change','fold_change'].filter(x=>x!==primary&&metrics.some(r=>Number.isFinite(+r[x]))))");
fs.writeFileSync('js/dashboard.js',dashboard);

let browserTest=fs.readFileSync('tests/browser-smoke.mjs','utf8');
browserTest=browserTest.replace("await analyzePreset(inputPage,'daily');assert.ok(window!==undefined);","await analyzePreset(inputPage,'daily');assert.ok((await inputPage.locator('#visualDashboard .main-svg').count())>=4,'TSV daily renders report');");
const oldWait="async function uploadAndWait(page,files,minRows=1){\n  await page.setInputFiles('#dataFiles',files);\n  await page.waitForFunction(n=>window.YeastFit?.S?.raw?.length>=n,minRows);\n}";
const newWait="async function uploadAndWait(page,files,minRows=1){\n  const list=Array.isArray(files)?files:[files];\n  const names=list.map(x=>typeof x==='string'?x.split('/').at(-1):x.name);\n  await page.setInputFiles('#dataFiles',files);\n  await page.waitForFunction(({names,minRows})=>window.YeastFit?.S?.raw?.length>=minRows&&window.YeastFit.S.files.length===names.length&&names.every(n=>window.YeastFit.S.files.includes(n)),{names,minRows});\n}";
if(browserTest.includes(oldWait))browserTest=browserTest.replace(oldWait,newWait);
browserTest=browserTest.replace("// Pasted table path.\nawait inputPage.locator('#pasteArea').fill(endpointCsv);","// Pasted table path.\nawait inputPage.evaluate(()=>window.YeastFit.step(1));\nawait inputPage.locator('.paste-box').evaluate(el=>el.open=true);\nawait inputPage.locator('#pasteArea').fill(endpointCsv);");
browserTest=browserTest.replace("// Pasted table path.\nawait inputPage.locator('.paste-box').evaluate(el=>el.open=true);\nawait inputPage.locator('#pasteArea').fill(endpointCsv);","// Pasted table path.\nawait inputPage.evaluate(()=>window.YeastFit.step(1));\nawait inputPage.locator('.paste-box').evaluate(el=>el.open=true);\nawait inputPage.locator('#pasteArea').fill(endpointCsv);");
const scenarioAnchor="  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);\n  assert.ok(overflow<=6,`${id}: horizontal overflow ${overflow}px`);";
const scenarioChecks="  const overview=await page.evaluate(()=>Object.fromEntries([...document.querySelectorAll('.analysis-overview-grid>div')].map(x=>[x.querySelector('small')?.textContent?.trim(),x.querySelector('b')?.textContent?.trim()])));\n  if(window===undefined){}\n  if(await page.evaluate(()=>Boolean(window.YeastFit.S.design.techRepField))){\n    assert.ok(Number(overview['Biological-level rows'])<Number(overview['Measurements']),`${id}: technical replicates must collapse before biological inference`);\n  }\n  if(['endpoint','screen'].includes(id)){\n    const headers=await page.locator('[data-analysis-module=\"timepoints\"] th').allTextContents();\n    assert.ok(!headers.some(h=>h.trim().toLowerCase()==='time'),`${id}: endpoint summaries must not contain meaningless time columns`);\n  }\n  if(id==='endpoint')assert.equal(Number(overview['Biological-level rows']),16,'endpoint demo should contain 16 biological-level observations');\n  if(id==='screen')assert.equal(Number(overview['Biological-level rows']),39,'screen demo should contain 39 biological-level observations');\n  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);\n  assert.ok(overflow<=6,`${id}: horizontal overflow ${overflow}px`);";
if(browserTest.includes(scenarioAnchor)&&!browserTest.includes('endpoint demo should contain 16'))browserTest=browserTest.replace(scenarioAnchor,scenarioChecks);
browserTest=browserTest.replace("  if(window===undefined){}\n",'');
fs.writeFileSync('tests/browser-smoke.mjs',browserTest);

const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));pkg.version='0.5.0';pkg.scripts.check='node --check js/analysis.js && node --check js/data.js && node --check js/stats.js && node --check js/comprehensive.js && node --check js/app.js && node --check js/demo-catalog.js && node --check js/templates.js && node --check js/presets.js && node --check js/workflow-v05.js && node --check js/dashboard.js && node --check js/advanced.js';pkg.scripts['test:browser']='node tests/browser-smoke.mjs';fs.writeFileSync('package.json',JSON.stringify(pkg,null,2)+'\n');

let readme=fs.readFileSync('README.md','utf8');
const note='\n## Unified setup and input templates\n\nYeastFit uses a single Setup page for data import, experiment selection, replicate/control mapping, and design review. Downloadable CSV and Excel templates are provided for every preset experiment plus a generic custom format and a 96-well plate-map template.\n\n## Visual report\n\nEvery supported experiment receives a comprehensive core report covering biological-level magnitude, group estimates with uncertainty, matched-control normalization when defined, effect sizes and FDR, biological sample size, QC, ranking, and metric relationships when available. Design-specific plots are added on top of this common report.\n';
if(!readme.includes('## Unified setup and input templates'))readme+=note;fs.writeFileSync('README.md',readme);
