import fs from 'node:fs';

function replaceOnce(text,needle,repl){if(!text.includes(needle))throw new Error(`Missing patch target: ${needle}`);return text.replace(needle,repl)}

let html=fs.readFileSync('index.html','utf8');
if(!html.includes('styles-v05.css'))html=replaceOnce(html,'  <link rel="stylesheet" href="styles-advanced.css" />','  <link rel="stylesheet" href="styles-advanced.css" />\n  <link rel="stylesheet" href="styles-v05.css" />');
if(!html.includes('workflow-v05.js'))html=replaceOnce(html,'  <script type="module" src="js/presets.js"></script>','  <script type="module" src="js/presets.js"></script>\n  <script type="module" src="js/workflow-v05.js"></script>');
fs.writeFileSync('index.html',html);

let advanced=fs.readFileSync('js/advanced.js','utf8');
const oldKeys=`function biologicalKeyFields(rows, includeTime=true) {\n  const candidate=[...(S.factors||[]),S.design.controlField,...(S.design.controlStrata||[]),S.design.bioRepField,S.design.batchField,fieldByName(rows,/^sample$|sample_id|culture_id/i),includeTime?'time':''].filter(Boolean);\n  return uniq(candidate).filter(f=>f!==S.design.techRepField&&has(rows,f));\n}`;
const newKeys=`function biologicalKeyFields(rows, includeTime=true) {\n  const sampleFallback=S.design.bioRepField?'':fieldByName(rows,/^sample$|sample_id|culture_id/i);\n  const timeKey=includeTime&&rows.some(r=>Number.isFinite(+r.time))?'time':'';\n  const candidate=[...(S.factors||[]),S.design.controlField,...(S.design.controlStrata||[]),S.design.bioRepField,S.design.batchField,sampleFallback,timeKey].filter(Boolean);\n  return uniq(candidate).filter(f=>f!==S.design.techRepField&&has(rows,f));\n}`;
if(advanced.includes(oldKeys))advanced=advanced.replace(oldKeys,newKeys);
const helperAnchor=`function fieldByName(rows,re){return fields(rows).find(f=>re.test(f))||'';}\nfunction collapseTechnical(rows,valueField,includeTime=true) {`;
const helperReplacement=`function fieldByName(rows,re){return fields(rows).find(f=>re.test(f))||'';}\nfunction reportStrata(strata=[]){return uniq(strata.filter(f=>!/(^|_)(plate|batch|run|experiment)(_|$)/i.test(f)));}\nfunction collapseMetricTable(rows){\n  if(!rows?.length||!S.design.techRepField||!has(rows,S.design.techRepField))return rows||[];\n  const keys=biologicalKeyFields(rows,false);\n  if(!keys.length)return rows;\n  const numeric=fields(rows).filter(f=>!keys.includes(f)&&f!==S.design.techRepField&&f!=='source_row'&&rows.some(r=>Number.isFinite(+r[f])));\n  const out=[];\n  for(const g of groupRows(rows,keys).values()){\n    const r={...Object.fromEntries(keys.map(k=>[k,g[0][k]??'']))};\n    for(const f of numeric){const v=g.map(x=>+x[f]).filter(Number.isFinite);if(v.length)r[f]=median(v);}\n    const flags=uniq(g.flatMap(x=>String(x.qc_flags||'').split(/[;,|]/).map(y=>y.trim()).filter(Boolean)));\n    if(flags.length)r.qc_flags=flags.join('; ');\n    r.technical_n=g.length;out.push(r);\n  }\n  return out;\n}\nfunction collapseTechnical(rows,valueField,includeTime=true) {`;
if(advanced.includes(helperAnchor)&&!advanced.includes('function collapseMetricTable'))advanced=advanced.replace(helperAnchor,helperReplacement);

const oldRank=`  const scored=robustScreen(rows,{metric,controlField:cfg.controlField,controlValue:cfg.controlValue,strata:cfg.strata,lowerIsDefect:true});\n  const keys=uniq([group,...cfg.strata,cfg.controlField].filter(Boolean));\n  const out=[];\n  for(const g of groupRows(scored,keys).values()){\n    const rel=g.map(r=>+r.relative_fitness).filter(Number.isFinite),z=g.map(r=>+r.robust_z).filter(Number.isFinite);\n    const base=Object.fromEntries(keys.map(k=>[k,g[0][k]??'']));\n    out.push({...base,biological_n:g.length,relative_fitness:rel.length?median(rel):NaN,mean_relative_fitness:rel.length?rel.reduce((a,b)=>a+b,0)/rel.length:NaN,median_robust_z:z.length?median(z):NaN,candidate_flag:z.length&&Math.abs(median(z))>=2?'candidate':''});\n  }`;
const newRank=`  const scored=robustScreen(rows,{metric,controlField:cfg.controlField,controlValue:cfg.controlValue,strata:cfg.strata,lowerIsDefect:true});\n  const displayStrata=reportStrata(cfg.strata).filter(f=>uniq(scored.map(r=>r[f])).length>1);\n  const keys=uniq([group,...displayStrata,cfg.controlField].filter(Boolean));\n  const out=[];\n  for(const g of groupRows(scored,keys).values()){\n    const rel=g.map(r=>+r.relative_fitness).filter(Number.isFinite),z=g.map(r=>+r.robust_z).filter(Number.isFinite);\n    const base=Object.fromEntries(keys.map(k=>[k,g[0][k]??'']));\n    const report_label=[String(g[0][group]??''),...displayStrata.map(f=>String(g[0][f]??''))].filter(Boolean).join(' · ');\n    out.push({...base,report_label,biological_n:g.length,relative_fitness:rel.length?median(rel):NaN,mean_relative_fitness:rel.length?rel.reduce((a,b)=>a+b,0)/rel.length:NaN,median_robust_z:z.length?median(z):NaN,candidate_flag:z.length&&Math.abs(median(z))>=2?'candidate':''});\n  }`;
if(advanced.includes(oldRank))advanced=advanced.replace(oldRank,newRank);

const oldComprehensive=`  const mode=S.design.analysisModeResolved||'endpoint',cfg=controlConfig(),group=preferredGroup(),rawPts=pointRows(),metric=metricForMode();\n  const pts=collapseTechnical(rawPts,'value',true),metrics=metric?collapseTechnical(S.metrics,metric,false):S.metrics;\n  const out={};\n  const pointGroupFields=uniq([group,...cfg.strata,'time'].filter(Boolean));\n  out.timepointSummary=pts.length?summarizeBy(pts,pointGroupFields,'value'):[];\n  out.normalizedPoints=pts.length&&cfg.controlField?controlNormalize(pts,'value',{...cfg,strata:uniq([...cfg.strata,'time'])}):[];\n  out.timepointTests=pts.length&&group?filteredTests(pts,'value',group,cfg,uniq([...cfg.strata,'time'])):[];\n  out.replicates=rawPts.length?replicateDiagnostics(rawPts,{technicalField:S.design.techRepField,biologicalField:S.design.bioRepField,timeField:'time',groupingFields:uniq([group,...cfg.strata].filter(Boolean)),cvWarn:0.15}):[];\n  out.metricSummary=metric&&group?summarizeBy(metrics,uniq([group,...cfg.strata].filter(Boolean)),metric):[];\n  out.metricTests=metric&&group?filteredTests(metrics,metric,group,cfg,cfg.strata):[];`;
const newComprehensive=`  const mode=S.design.analysisModeResolved||'endpoint',cfg=controlConfig(),group=preferredGroup(),rawPts=pointRows(),metric=metricForMode();\n  const pts=collapseTechnical(rawPts,'value',true),metrics=collapseMetricTable(S.metrics);\n  const out={},hasTime=pts.some(r=>Number.isFinite(+r.time)),summaryStrata=reportStrata(cfg.strata);\n  const pointNormStrata=uniq([...cfg.strata,hasTime?'time':''].filter(Boolean));\n  const pointTestStrata=uniq([...summaryStrata,hasTime?'time':''].filter(Boolean));\n  const pointGroupFields=uniq([group,...pointTestStrata].filter(Boolean));\n  out.timepointSummary=pts.length?summarizeBy(pts,pointGroupFields,'value'):[];\n  out.normalizedPoints=pts.length&&cfg.controlField?controlNormalize(pts,'value',{...cfg,strata:pointNormStrata}):[];\n  out.timepointTests=out.normalizedPoints.length&&group?filteredTests(out.normalizedPoints,'relative_to_control',group,cfg,pointTestStrata):[];\n  out.replicates=rawPts.length?replicateDiagnostics(rawPts,{technicalField:S.design.techRepField,biologicalField:S.design.bioRepField,timeField:hasTime?'time':'',groupingFields:uniq([group,...summaryStrata].filter(Boolean)),cvWarn:0.15}):[];\n  out.metricSummary=metric&&group?summarizeBy(metrics,uniq([group,...summaryStrata].filter(Boolean)),metric):[];\n  out.normalizedMetrics=metric&&cfg.controlField?controlNormalize(metrics,metric,cfg):[];\n  out.metricTests=metric&&group&&out.normalizedMetrics.length?filteredTests(out.normalizedMetrics,'relative_to_control',group,cfg,summaryStrata):[];`;
if(advanced.includes(oldComprehensive))advanced=advanced.replace(oldComprehensive,newComprehensive);
const intermediateComprehensive=`  const mode=S.design.analysisModeResolved||'endpoint',cfg=controlConfig(),group=preferredGroup(),rawPts=pointRows(),metric=metricForMode();\n  const pts=collapseTechnical(rawPts,'value',true),metrics=metric?collapseTechnical(S.metrics,metric,false):S.metrics;\n  const out={};\n  const hasTime=pts.some(r=>Number.isFinite(+r.time));\n  const pointStrata=uniq([...cfg.strata,hasTime?'time':''].filter(Boolean));\n  const pointGroupFields=uniq([group,...pointStrata].filter(Boolean));\n  out.timepointSummary=pts.length?summarizeBy(pts,pointGroupFields,'value'):[];\n  out.normalizedPoints=pts.length&&cfg.controlField?controlNormalize(pts,'value',{...cfg,strata:pointStrata}):[];\n  out.timepointTests=pts.length&&group?filteredTests(pts,'value',group,cfg,pointStrata):[];\n  out.replicates=rawPts.length?replicateDiagnostics(rawPts,{technicalField:S.design.techRepField,biologicalField:S.design.bioRepField,timeField:hasTime?'time':'',groupingFields:uniq([group,...cfg.strata].filter(Boolean)),cvWarn:0.15}):[];\n  out.metricSummary=metric&&group?summarizeBy(metrics,uniq([group,...cfg.strata].filter(Boolean)),metric):[];\n  out.metricTests=metric&&group?filteredTests(metrics,metric,group,cfg,cfg.strata):[];`;
if(advanced.includes(intermediateComprehensive))advanced=advanced.replace(intermediateComprehensive,newComprehensive);

const oldCompareTime=`      const rows=collapseTechnical(pointRows(),'value',true),strata=uniq([...cfg.strata,'time']);\n      S.norm=normalizeToControls(rows,'value',{...cfg,strata});S.cmp=filteredTests(rows,'value',g,cfg,strata);`;
const newCompareTime=`      const rows=collapseTechnical(pointRows(),'value',true),hasTime=rows.some(r=>Number.isFinite(+r.time)),normStrata=uniq([...cfg.strata,hasTime?'time':''].filter(Boolean)),testStrata=uniq([...reportStrata(cfg.strata),hasTime?'time':''].filter(Boolean));\n      S.norm=normalizeToControls(rows,'value',{...cfg,strata:normStrata});S.cmp=filteredTests(S.norm,'value_relative',g,cfg,testStrata);`;
if(advanced.includes(oldCompareTime))advanced=advanced.replace(oldCompareTime,newCompareTime);
const oldCompareMetric=`    const rows=collapseTechnical(S.metrics,m,false);S.norm=normalizeToControls(rows,m,cfg);S.cmp=filteredTests(rows,m,g,cfg,cfg.strata);$('#comparisonTable').innerHTML=tableHtml(S.cmp,200);`;
const newCompareMetric=`    const rows=collapseMetricTable(S.metrics);S.norm=normalizeToControls(rows,m,cfg);S.cmp=filteredTests(S.norm,\`${'${m}'}_relative\`,g,cfg,reportStrata(cfg.strata));$('#comparisonTable').innerHTML=tableHtml(S.cmp,200);`;
if(advanced.includes(oldCompareMetric))advanced=advanced.replace(oldCompareMetric,newCompareMetric);

advanced=advanced.replace("tables={};const data=comprehensiveData(),mode=S.design.analysisModeResolved||'endpoint',group=preferredGroup(),metric=metricForMode(),preset=S.design.presetName||'Automatic / custom';","tables={};const data=comprehensiveData(),mode=S.design.analysisModeResolved||'endpoint',group=preferredGroup(),metric=metricForMode(),preset=S.design.presetName||'Automatic / custom',hasTime=data.inferencePoints.some(r=>Number.isFinite(+r.time));");
advanced=advanced.replace("section('timepoints','Timepoint summaries','Biological-level mean, median, SD, SEM, 95% CI, CV, range, and n for each relevant group and timepoint.',data.timepointSummary)","section('timepoints',hasTime?'Timepoint summaries':'Observation summaries',hasTime?'Biological-level mean, median, SD, SEM, 95% CI, CV, range, and n for each relevant group and sampled timepoint.':'Biological-level mean, median, SD, SEM, 95% CI, CV, range, and n for each relevant group.',data.timepointSummary)");
fs.writeFileSync('js/advanced.js',advanced);

let dashboard=fs.readFileSync('js/dashboard.js','utf8');
const bad="z:ls.map(g=>times.map(t=>med(rows.filter(r=>r[group]===g&&+r.time===t).map(r=>r.relative_to_control))),zmid:1";
const good="z:ls.map(g=>times.map(t=>med(rows.filter(r=>r[group]===g&&+r.time===t).map(r=>r.relative_to_control)))),zmid:1";
if(dashboard.includes(bad))dashboard=dashboard.replace(bad,good);
dashboard=dashboard.replace("a.map(r=>String(r[group]??r.rank))","a.map(r=>String(r.report_label??r[group]??r.rank))");
dashboard=dashboard.replace("for(const m of ['endpoint','auc','trend_slope','absolute_change','fold_change'].filter(x=>metrics.some(r=>Number.isFinite(+r[x]))))","for(const m of ['endpoint','auc','trend_slope','absolute_change','fold_change'].filter(x=>x!==primary&&metrics.some(r=>Number.isFinite(+r[x]))))");
fs.writeFileSync('js/dashboard.js',dashboard);

let browserTest=fs.readFileSync('tests/browser-smoke.mjs','utf8');
browserTest=browserTest.replace("await analyzePreset(inputPage,'daily');assert.ok(window!==undefined);","await analyzePreset(inputPage,'daily');assert.ok((await inputPage.locator('#visualDashboard .main-svg').count())>=4,'TSV daily renders report');");
const oldWait="async function uploadAndWait(page,files,minRows=1){\n  await page.setInputFiles('#dataFiles',files);\n  await page.waitForFunction(n=>window.YeastFit?.S?.raw?.length>=n,minRows);\n}";
const newWait="async function uploadAndWait(page,files,minRows=1){\n  const list=Array.isArray(files)?files:[files];\n  const names=list.map(x=>typeof x==='string'?x.split('/').at(-1):x.name);\n  await page.setInputFiles('#dataFiles',files);\n  await page.waitForFunction(({names,minRows})=>window.YeastFit?.S?.raw?.length>=minRows&&window.YeastFit.S.files.length===names.length&&names.every(n=>window.YeastFit.S.files.includes(n)),{names,minRows});\n}";
if(browserTest.includes(oldWait))browserTest=browserTest.replace(oldWait,newWait);
browserTest=browserTest.replace("// Pasted table path.\nawait inputPage.locator('#pasteArea').fill(endpointCsv);","// Pasted table path.\nawait inputPage.evaluate(()=>window.YeastFit.step(1));\nawait inputPage.locator('.paste-box').evaluate(el=>el.open=true);\nawait inputPage.locator('#pasteArea').fill(endpointCsv);");
browserTest=browserTest.replace("// Pasted table path.\nawait inputPage.locator('.paste-box').evaluate(el=>el.open=true);\nawait inputPage.locator('#pasteArea').fill(endpointCsv);","// Pasted table path.\nawait inputPage.evaluate(()=>window.YeastFit.step(1));\nawait inputPage.locator('.paste-box').evaluate(el=>el.open=true);\nawait inputPage.locator('#pasteArea').fill(endpointCsv);");
const scenarioAnchor="  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);\n  assert.ok(overflow<=6,`${id}: horizontal overflow ${overflow}px`);";
const scenarioChecks="  const overview=await page.evaluate(()=>Object.fromEntries([...document.querySelectorAll('.analysis-overview-grid>div')].map(x=>[x.querySelector('small')?.textContent?.trim(),x.querySelector('b')?.textContent?.trim()])));\n  if(await page.evaluate(()=>Boolean(window.YeastFit.S.design.techRepField))){\n    assert.ok(Number(overview['Biological-level rows'])<Number(overview['Measurements']),`${id}: technical replicates must collapse before biological inference`);\n  }\n  if(['endpoint','screen'].includes(id)){\n    const headers=await page.locator('[data-analysis-module=\"timepoints\"] th').allTextContents();\n    assert.ok(!headers.some(h=>h.trim().toLowerCase()==='time'),`${id}: endpoint summaries must not contain meaningless time columns`);\n  }\n  if(['endpoint','screen','matrix'].includes(id)){\n    const summaryText=await page.locator('[data-analysis-module=\"timepoints\"]').innerText();\n    assert.ok(!/\\bNaN\\b/.test(summaryText),`${id}: biological summaries should not be fragmented into n=1 batch strata`);\n  }\n  if(id==='endpoint')assert.equal(Number(overview['Biological-level rows']),16,'endpoint demo should contain 16 biological-level observations');\n  if(id==='screen')assert.equal(Number(overview['Biological-level rows']),39,'screen demo should contain 39 biological-level observations');\n  if(id==='matrix')assert.ok(await page.locator('#viz_effects .main-svg').count()===1,'matrix should produce matched-control effect statistics');\n  if(id==='daily'){assert.ok(await page.locator('#viz_serial_auc .main-svg').count()===1,'daily report should include AUC');assert.ok(await page.locator('#viz_serial_trend_slope .main-svg').count()===1,'daily report should include longitudinal slope');}\n  if(id==='kinetic'){assert.ok(await page.locator('#viz_metric_auc .main-svg').count()===1,'kinetic report should include AUC');assert.ok(await page.locator('#viz_metric_doubling_time .main-svg').count()===1,'kinetic report should include doubling time');assert.ok(await page.locator('#viz_metric_lag .main-svg').count()===1,'kinetic report should include lag');}\n  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);\n  assert.ok(overflow<=6,`${id}: horizontal overflow ${overflow}px`);";
if(browserTest.includes(scenarioAnchor)&&!browserTest.includes('endpoint demo should contain 16'))browserTest=browserTest.replace(scenarioAnchor,scenarioChecks);
else if(browserTest.includes('endpoint demo should contain 16')&&!browserTest.includes('daily report should include AUC')){
  browserTest=browserTest.replace("  if(id==='screen')assert.equal(Number(overview['Biological-level rows']),39,'screen demo should contain 39 biological-level observations');","  if(id==='screen')assert.equal(Number(overview['Biological-level rows']),39,'screen demo should contain 39 biological-level observations');\n  if(['endpoint','screen','matrix'].includes(id)){const summaryText=await page.locator('[data-analysis-module=\"timepoints\"]').innerText();assert.ok(!/\\bNaN\\b/.test(summaryText),`${id}: biological summaries should not be fragmented into n=1 batch strata`);}\n  if(id==='matrix')assert.ok(await page.locator('#viz_effects .main-svg').count()===1,'matrix should produce matched-control effect statistics');\n  if(id==='daily'){assert.ok(await page.locator('#viz_serial_auc .main-svg').count()===1,'daily report should include AUC');assert.ok(await page.locator('#viz_serial_trend_slope .main-svg').count()===1,'daily report should include longitudinal slope');}\n  if(id==='kinetic'){assert.ok(await page.locator('#viz_metric_auc .main-svg').count()===1,'kinetic report should include AUC');assert.ok(await page.locator('#viz_metric_doubling_time .main-svg').count()===1,'kinetic report should include doubling time');assert.ok(await page.locator('#viz_metric_lag .main-svg').count()===1,'kinetic report should include lag');}");
}
browserTest=browserTest.replace("  if(window===undefined){}\n",'');
fs.writeFileSync('tests/browser-smoke.mjs',browserTest);

const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));pkg.version='0.5.0';pkg.scripts.check='node --check js/analysis.js && node --check js/data.js && node --check js/stats.js && node --check js/comprehensive.js && node --check js/app.js && node --check js/demo-catalog.js && node --check js/templates.js && node --check js/presets.js && node --check js/workflow-v05.js && node --check js/dashboard.js && node --check js/advanced.js';pkg.scripts['test:browser']='node tests/browser-smoke.mjs';fs.writeFileSync('package.json',JSON.stringify(pkg,null,2)+'\n');

let readme=fs.readFileSync('README.md','utf8');
const note='\n## Unified setup and input templates\n\nYeastFit uses a single Setup page for data import, experiment selection, replicate/control mapping, and design review. Downloadable CSV and Excel templates are provided for every preset experiment plus a generic custom format and a 96-well plate-map template.\n\n## Visual report\n\nEvery supported experiment receives a comprehensive core report covering biological-level magnitude, group estimates with uncertainty, matched-control normalization when defined, effect sizes and FDR, biological sample size, QC, ranking, and metric relationships when available. Design-specific plots are added on top of this common report. Technical replicates are collapsed before biological inference, while matched-control normalization can retain plate/batch structure without fragmenting biological summaries into one-observation strata.\n';
if(!readme.includes('## Unified setup and input templates'))readme+=note;fs.writeFileSync('README.md',readme);
